name: nuSQuIDS
channels:
    - conda-forge
dependencies:
    - boost
    - python 
    - jupyter
    - matplotlib
    - numpy
    - ipython
    - pytables
    - jupyterlab
    - libgcc
    - gnuplot
    - gsl